<a href="https://colab.research.google.com/github/shruthymenon/Numpy-Task-2/blob/main/NUMPY_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#1. Import the numpy package under the name np
import numpy as np

In [3]:
#2.Print the numpy version and the configuration
np.__version__

'1.21.6'

In [ ]:
#3.Create a null vector of size 10
a=np.zeros(10,dtype='int' )
a


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#4.How to find the memory size of any array 

print(a.size,a.itemsize)#total no of elements #memory size of elements


10 8


In [ ]:
#5. How to get the documentation of the numpy add function from the command line? (★☆☆)
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7f2099256690>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

In [ ]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
#7. Create a vector with values ranging from 10 to 49 (★☆☆)
b=np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#8 Reverse a vector (first element becomes last) (★☆☆)
print(b[::-1])


[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#10.Find indices of non-zero elements from [1,2,0,0,4,0]
a=[1,2,0,0,4,0]
for i in range(6):
  if a[i]!=0:
    print(i)

0
1
4


In [ ]:
#11.Create a 3x3 identity matrix 
a=np.eye(3,3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#12. Create a 3x3x3 array with random values
a=np.random.randint(0,100,size=(3,3,3))
print(a)

[[[25 71  2]
  [53 29 24]
  [83 18 44]]

 [[43 19 31]
  [31 77 16]
  [26 52 56]]

 [[16 10 39]
  [48 63 89]
  [34  2 67]]]


In [ ]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
a=np.random.rand(10,10)
print(a)
print(np.min(a))
print(np.max(a))

[[0.68055732 0.34932115 0.72055618 0.60015099 0.45612887 0.09396673
  0.08792159 0.40665425 0.89317968 0.08864326]
 [0.70556124 0.10415343 0.77493821 0.36505726 0.95874182 0.51956958
  0.45596424 0.04628309 0.3023252  0.60905418]
 [0.82091772 0.70441783 0.8459032  0.09512494 0.29719704 0.19217964
  0.22782834 0.54618979 0.28657282 0.60627814]
 [0.86188016 0.02570064 0.83833088 0.72425815 0.64090552 0.29074685
  0.91922232 0.18788372 0.86948121 0.18176173]
 [0.7504528  0.96312466 0.32138575 0.55835211 0.58142201 0.39286009
  0.11587764 0.28267463 0.79363703 0.2979257 ]
 [0.45476565 0.51296809 0.20496756 0.00270545 0.68095483 0.7645804
  0.68432064 0.95035496 0.40426233 0.79205647]
 [0.45337578 0.37372135 0.29387134 0.84670335 0.13801314 0.94158006
  0.54551409 0.62456065 0.57526497 0.08406823]
 [0.89858645 0.10872294 0.30928597 0.41281744 0.53862544 0.02071037
  0.03575563 0.71206325 0.40015716 0.84232461]
 [0.08809693 0.49868273 0.79253233 0.88617268 0.81929175 0.98799053
  0.92881116 

In [ ]:
#14.Create a random vector of size 30 and find the mean value 
a=np.random.randint(0,100,size=(30))
print(a)
print(np.mean(a))

[78 50 81  6 66  1 76 49 70 62 62 61 23 99 37 13 63 35 18 73 51  0  2 22
 86 11 22 79 99  2]
46.56666666666667


In [ ]:
#15. Create a 2d array with 1 on the border and 0 inside
a=np.ones([6,6],dtype=int)
print(a)
b=np.zeros([4,4],dtype=int)
print(b)
a[1:-1,1:-1]=b
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [ ]:
#16. How to add a border (filled with 0's) around an existing array? 
import numpy as np
a= np.random.randint(1,200,size=(6,6),dtype='int32')
print(a)
b=np.zeros((4,4))
a[:,0]= 0; a[0,:]=0;a[-1,:]=0;a[:,-1]=0
print(a)

[[ 70  15 189 137 151 177]
 [166 152  76  90 110  11]
 [ 73 105  46 195   3 169]
 [145 143 103 114  27  27]
 [ 86 199  28  79  79 124]
 [171 199   9   1  11  74]]
[[  0   0   0   0   0   0]
 [  0 152  76  90 110   0]
 [  0 105  46 195   3   0]
 [  0 143 103 114  27   0]
 [  0 199  28  79  79   0]
 [  0   0   0   0   0   0]]


In [ ]:
#17. What is the result of the following expression?
#(hint: NaN = not a number, inf = infinity)
import numpy as np
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [ ]:
#18.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
import numpy as np
a= np.zeros((5,5) )
print(a)
j=1;k=1
for i in range(1,5):
  a[i,j-1] = k  
  j=j+1;k+=1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
#19 Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
a=np.zeros((8,8))
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#20.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import numpy as np
a=np.ones((6,7,8))
m=0
for i in range(6):
  for j in range (7):
    for k in range(8):
      
      if(m==100):
       break
      m=m+1
print(i,j,k)

5 6 0


In [ ]:
#21.Create a checkerboard 8x8 matrix using the tile function
import numpy as np
A = np.array([[[[[[[[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]]]]]]]])
x = np.tile(A,reps=4)
print(x)

[[[[[[[[0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]]]]]]]]


In [ ]:
#22. Normalize a 5x5 random matrix
import numpy as np
a = np.random.rand(5,5)
print(a)
min=np.min(a);max=np.max(a)
a=(a-min)/(max-min)
print(a)

[[0.43042404 0.50507407 0.36347196 0.49910119 0.487247  ]
 [0.79752548 0.94031071 0.45485252 0.90436461 0.79006394]
 [0.56950445 0.88790466 0.11063609 0.09044992 0.14063367]
 [0.61368756 0.57738413 0.89225384 0.27846316 0.68639694]
 [0.94043441 0.57195446 0.60613172 0.75258775 0.3179559 ]]
[[0.39997685 0.48780202 0.32120826 0.48077498 0.46682862]
 [0.83186879 0.99985447 0.42871677 0.95756417 0.82309034]
 [0.56360384 0.93819917 0.02374886 0.         0.05904078]
 [0.61558492 0.57287422 0.94331594 0.22119608 0.70112693]
 [1.         0.56648627 0.60669554 0.7789999  0.26765898]]


In [ ]:
#23.Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [ ]:
#25.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#27. Consider an integer vector Z, which of these expressions are legal? 
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

ValueError: ignored

In [ ]:
# 28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-9.22337204e+18])

In [ ]:
# 29. How to round away from zero a float array ? (★☆☆)
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)


array([ 8.,  7., 10., -7., -9.,  9.,  2., -3.,  4., -8.])

In [ ]:
# 30. How to find common values between two arrays? (★☆☆)
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

In [ ]:
# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [ ]:
# 32. Is the following expressions true? (★☆☆)
print(np.sqrt(-1) == np.emath.sqrt(-1))  # False

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


In [ ]:
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
today = np.datetime64('today', 'D')
print("Today: ", today)
  
# for yesterday
yesterday = np.datetime64('today', 'D')
- np.timedelta64(1, 'D')
  
print("Yestraday: ", yesterday)
  
# for tomorrow
tomorrow = np.datetime64('today', 'D')
+ np.timedelta64(1, 'D')
  
print("Tomorrow: ", tomorrow)

Today:  2022-11-23
Yestraday:  2022-11-23
Tomorrow:  2022-11-23


In [ ]:
# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
# 36. Extract the integer part of a random array using 5 different methods (★★☆)
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)

array([-3.,  5., -7., -5.,  3.,  4.,  0.,  3.,  9., -8.])

In [ ]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
np.linspace(start=0, stop=11, num=10, endpoint=False)

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

In [ ]:
# 40. Create a random vector of size 10 and sort it (★★☆)
x = np.random.random(size=10)
x.sort()
print(x)

[0.02392405 0.05441597 0.14486998 0.18435972 0.39919631 0.53631181
 0.58710137 0.60210088 0.79940244 0.85677584]


In [ ]:
 #41. How to sum a small array faster than np.sum? (★★☆)
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

6.185054779052734
8.404970169067383


In [ ]:
# 42. Consider two random array A and B, check if they are equal (★★☆)
A = np.arange(10)
B = np.arange(10)
np.array_equal(A, B)

True

In [ ]:
 #43. Make an array immutable (read-only) (★★☆)
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1   # ValueError: assignment destination is read-only

ValueError: ignored

In [ ]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)


[0.83465029 1.19458474 1.16385554 0.09182107 0.93379693 0.37344846
 1.23376247 0.49395683 0.60028364 0.92147988]
[0.86086722 0.75657596 0.67902896 0.32284366 0.76062342 0.83139017
 0.66619657 1.29650312 1.20787928 0.77105275]


In [ ]:
# 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
x = np.random.random(10)
x[x == np.max(x)] = 0
x[x.argmax()] = 0
print(x)

[0.         0.23069277 0.77608753 0.         0.44664191 0.28365092
 0.27140319 0.13167547 0.57862439 0.80292021]


In [ ]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ 1.60057360e+04, -6.29045400e+07,  9.49623212e+06,
         6.81631403e+05, -1.23204027e+05],
       [-1.91753274e+06,  8.25142398e+04, -9.61777493e+02,
         1.13869446e+08,  5.94705171e+01],
       [ 2.06949745e+05, -8.78053127e+05, -1.46274167e+05,
        -1.40221101e+05,  2.66586052e+05],
       [-6.94427096e+06,  2.59124236e+05, -9.38972041e+06,
         8.25216872e+00, -3.47879616e+06],
       [ 2.92253665e+07, -4.37467580e+04, -1.88134204e+04,
         1.37837031e+04,  3.18776718e+02]])

In [ ]:
#48.Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps) 

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
#49. How to print all the values of an array? (★★☆)
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: ignored

In [ ]:
# 50 How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

57


In [ ]:
#51 Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [ ]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.79025772 0.90167508 0.49359852 0.71070945 0.85920451
  0.83175248 0.44097399 0.88745122 1.22279051]
 [0.79025772 0.         0.19697883 0.30187602 0.69137112 0.22117059
  0.0416209  0.40894519 0.32789758 0.66642715]
 [0.90167508 0.19697883 0.         0.41384224 0.62324639 0.06983676
  0.18390396 0.47291314 0.16447019 0.47044913]
 [0.49359852 0.30187602 0.41384224 0.         0.54063923 0.38126055
  0.3434154  0.13734739 0.43688749 0.80168201]
 [0.71070945 0.69137112 0.62324639 0.54063923 0.         0.55342053
  0.71758984 0.42262334 0.48437821 0.64858959]
 [0.85920451 0.22117059 0.06983676 0.38126055 0.55342053 0.
  0.22065856 0.42333621 0.10883047 0.45392712]
 [0.83175248 0.0416209  0.18390396 0.3434154  0.71758984 0.22065856
  0.         0.4487359  0.32939168 0.65384257]
 [0.44097399 0.40894519 0.47291314 0.13734739 0.42262334 0.42333621
  0.4487359  0.         0.44656179 0.79050896]
 [0.88745122 0.32789758 0.16447019 0.43688749 0.48437821 0.10883047
  0.32939168 0.44656

In [ ]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#54. How to read the following file? (★★☆)
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [ ]:
#55. What is the equivalent of enumerate for numpy arrays? (★★☆)
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
#56. Generate a generic 2D Gaussian-like array (★★☆)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [ ]:
#57. How to randomly place p elements in a 2D array? (★★☆)

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#58. Subtract the mean of each row of a matrix (★★☆)
X = np.random.rand(5, 10)


Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.40761483 -0.33149945  0.02196865 -0.41649107 -0.1478097   0.02893823
   0.51885444  0.07236445  0.07105961 -0.22499999]
 [-0.05782354  0.33356264  0.10523005 -0.22578726 -0.32010088 -0.29483608
   0.33073158  0.01748078  0.3243484  -0.21280568]
 [ 0.02366955  0.16948846 -0.51408182  0.04295907  0.14811642  0.41734827
  -0.09151031 -0.27144403 -0.07581525  0.15126964]
 [-0.03483535 -0.08071814 -0.01392362  0.06191373  0.27156191 -0.12002796
  -0.27057235  0.39341136 -0.57733118  0.3705216 ]
 [ 0.26562541 -0.27884935 -0.33357629  0.36156027  0.16226711  0.33689208
  -0.23342324  0.31642732 -0.28472055 -0.31220277]]


In [ ]:
#59. How to sort an array by the nth column? (★★☆)
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 0 4]
 [3 9 8]
 [9 3 6]]
[[7 0 4]
 [9 3 6]
 [3 9 8]]


In [ ]:
#60. How to tell if a given 2D array has null columns?
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [ ]:
#61. Find the nearest value from a given value in an array (★★☆)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4618884238132126


In [ ]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
#63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

In [ ]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 2. 4. 2. 2. 4. 6. 3. 2. 4.]


In [ ]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [ ]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[44 47 36 68]
 [48 43 58 32]
 [48 58 63 51]]
[[44 47 36 68]
 [48 43 58 32]
 [48 58 63 51]]


In [ ]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? 
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.41347166 0.4340333  0.50246364 0.50743584 0.39743589 0.43268291
 0.47515207 0.36939763 0.55716187 0.45252549]
0    0.413472
1    0.434033
2    0.502464
3    0.507436
4    0.397436
5    0.432683
6    0.475152
7    0.369398
8    0.557162
9    0.452525
dtype: float64


In [ ]:
#69. How to get the diagonal of a dot product?

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
  
np.diag(np.dot(A, B))

np.sum(A * B.T, axis=1)

np.einsum("ij,ji->i", A, B)

array([1.37583778, 1.38852276, 1.40339719, 0.98752047, 0.75101932])

In [ ]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [4]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [5]:
#72. How to swap two rows of an array? (★★★)

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)


faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1,  3) ( 1, 43) ( 1, 59) ( 1, 63) ( 2, 73) ( 2, 99) ( 3, 43) (13, 37)
 (13, 51) (37, 51) (41, 50) (41, 97) (49, 56) (49, 92) (50, 97) (52, 83)
 (52, 95) (53, 78) (53, 90) (56, 92) (59, 63) (68, 95) (68, 97) (70, 91)
 (70, 95) (73, 99) (78, 90) (83, 95) (91, 95) (95, 97)]


In [7]:
#74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [8]:
#75 How to compute averages using a sliding window over an array? (★★★)


def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [9]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [10]:
#77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.1619832 ,  0.64189756, -0.45293207, -0.33276533, -0.07466654,
       -0.98805939,  0.16133436, -0.24329881, -0.5255179 , -0.63710686,
       -0.58911778,  0.94291521, -0.86651181,  0.55539874, -0.27698005,
       -0.29353678, -0.38909563,  0.39516346, -0.57054647,  0.44842055,
        0.14491932, -0.93806969,  0.49517478,  0.04569727,  0.31837508,
       -0.05614323, -0.23596984,  0.86711671,  0.6032142 , -0.87163867,
       -0.89936131,  0.82753608,  0.38890327,  0.09704317,  0.00796865,
       -0.69244727,  0.52581814,  0.79271403, -0.8126071 ,  0.38733429,
       -0.44764848,  0.47689372, -0.92210761,  0.55904724, -0.03116621,
        0.61606535,  0.7457453 ,  0.19417421,  0.42452176,  0.09038732,
        0.54291327,  0.49099746,  0.42360592,  0.90863489,  0.96023406,
        0.80557977, -0.86531607,  0.07604674,  0.80686098, -0.4267149 ,
       -0.96807052, -0.39492136,  0.24910302, -0.3655365 , -0.29675558,
       -0.91593643,  0.79759777,  0.3257414 ,  0.92518736, -0.95

In [11]:
#78 Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.10569368 14.49992665 15.76449763  6.43994046 16.81907452 15.46129921
 14.15253195 12.11192035 16.53051405  2.34221041]


In [12]:
#79.Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.53251006  1.04436245  5.63143596  5.61313056  3.16348098  5.84797687
   4.84300821  7.46270675  7.0879518  15.4325784 ]
 [ 7.37786687  3.77314852  6.18879847  3.07988801  4.54517249  3.94903098
   2.11596483  4.68863218  6.13763331 13.32154147]
 [ 6.52429512 13.32994289  4.30371369  3.54146778  5.74201663  4.93380779
   5.93493803  3.95522702  0.46663195  4.05219838]
 [ 5.69923992  0.64202226  4.9742799   7.36208475  2.01277891  6.83959668
   6.65054258  9.26440625  7.40826242 16.58430576]
 [ 3.4573111   5.16316241  2.09542308  4.35693476  1.09409935  0.4351298
   2.43777357  4.49795083  1.91628946 10.10604663]
 [ 9.27198803 16.07277835  6.77332242  7.20767752  8.94318832  5.73170254
   9.42233271  7.27679668  0.20835282  2.86382985]
 [ 6.91401715  6.2961398   8.45984095  9.63195756  8.57086625  6.62872456
   5.52166828  6.35845777  7.68777565  3.9557054 ]
 [ 1.57137236 17.29139359  1.10439513  3.57238268  1.84648915 11.30759782
   7.46374681  6.24619582  7.15442292  2.05220164]
 

In [13]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 3 1 4 9 5 1 6 2 2]
 [5 4 9 5 2 1 6 8 3 8]
 [3 3 7 7 7 3 6 1 6 8]
 [3 7 3 2 1 4 8 9 4 2]
 [2 1 1 5 8 2 5 2 4 4]
 [7 0 6 3 7 9 0 4 7 7]
 [0 2 5 7 9 9 6 0 7 3]
 [5 4 8 6 3 6 0 6 4 9]
 [0 6 3 8 6 6 1 4 2 9]
 [4 5 6 0 0 2 6 3 9 0]]
[[0 0 0 0 0]
 [0 8 3 1 4]
 [0 5 4 9 5]
 [0 3 3 7 7]
 [0 3 7 3 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [14]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [15]:
#82. Compute a matrix rank (★★★)

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [16]:
#83.How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


In [17]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 1 2]
   [2 4 3]
   [2 2 3]]

  [[1 2 0]
   [4 3 0]
   [2 3 0]]

  [[2 0 0]
   [3 0 2]
   [3 0 3]]

  [[0 0 4]
   [0 2 0]
   [0 3 3]]

  [[0 4 1]
   [2 0 1]
   [3 3 0]]

  [[4 1 4]
   [0 1 1]
   [3 0 4]]

  [[1 4 2]
   [1 1 2]
   [0 4 0]]

  [[4 2 4]
   [1 2 3]
   [4 0 2]]]


 [[[2 4 3]
   [2 2 3]
   [4 2 4]]

  [[4 3 0]
   [2 3 0]
   [2 4 0]]

  [[3 0 2]
   [3 0 3]
   [4 0 1]]

  [[0 2 0]
   [0 3 3]
   [0 1 3]]

  [[2 0 1]
   [3 3 0]
   [1 3 4]]

  [[0 1 1]
   [3 0 4]
   [3 4 2]]

  [[1 1 2]
   [0 4 0]
   [4 2 2]]

  [[1 2 3]
   [4 0 2]
   [2 2 2]]]


 [[[2 2 3]
   [4 2 4]
   [1 1 1]]

  [[2 3 0]
   [2 4 0]
   [1 1 4]]

  [[3 0 3]
   [4 0 1]
   [1 4 3]]

  [[0 3 3]
   [0 1 3]
   [4 3 1]]

  [[3 3 0]
   [1 3 4]
   [3 1 2]]

  [[3 0 4]
   [3 4 2]
   [1 2 1]]

  [[0 4 0]
   [4 2 2]
   [2 1 2]]

  [[4 0 2]
   [2 2 2]
   [1 2 2]]]


 [[[4 2 4]
   [1 1 1]
   [4 2 1]]

  [[2 4 0]
   [1 1 4]
   [2 1 3]]

  [[4 0 1]
   [1 4 3]
   [1 3 2]]

  [[0 1 3]
   [4 3 1]
   [3 2 0]]

  [[1 3 4]
   

In [18]:
#85.Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  8 14 10  7]
 [ 8  6 15  6 11]
 [14 15  1 42  6]
 [10  6 42  2 12]
 [ 7 11  6 12  3]]


In [19]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [20]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [21]:
#88. How to implement the Game of Life using numpy arrays? (★★★)

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
#89.89. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


In [23]:
#90.Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [24]:
#91.How to create a record array from a regular array? (★★★)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [25]:
#92.Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: ignored

In [26]:
#93.Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[7]


In [27]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 2 1]
 [1 2 4]
 [0 4 2]
 [2 1 1]
 [2 1 2]
 [4 1 3]
 [1 4 4]
 [4 2 3]
 [2 3 0]
 [4 4 0]]
[[1 2 1]
 [1 2 4]
 [0 4 2]
 [2 1 1]
 [2 1 2]
 [4 1 3]
 [1 4 4]
 [4 2 3]
 [2 3 0]
 [4 4 0]]
[[1 2 1]
 [1 2 4]
 [0 4 2]
 [2 1 1]
 [2 1 2]
 [4 1 3]
 [1 4 4]
 [4 2 3]
 [2 3 0]
 [4 4 0]]


In [28]:
#95. Convert a vector of ints into a matrix binary representation (★★★)

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [29]:
#96.Given a two dimensional array, how to extract unique rows? (★★★)


Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]]
[[0 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


In [30]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[1.77637080e-03, 3.27354387e-03, 7.33593948e-03, 2.34557320e-03,
        4.40587991e-03, 3.07329306e-03, 7.72273306e-04, 4.22806467e-03,
        4.14223963e-03, 6.98004603e-03],
       [1.49825684e-01, 2.76102799e-01, 6.18740271e-01, 1.97834319e-01,
        3.71608209e-01, 2.59212904e-01, 6.51363872e-02, 3.56610614e-01,
        3.49371812e-01, 5.88722900e-01],
       [4.82580319e-02, 8.89311989e-02, 1.99292852e-01, 6.37213505e-02,
        1.19692968e-01, 8.34910566e-02, 2.09800735e-02, 1.14862325e-01,
        1.12530747e-01, 1.89624421e-01],
       [1.16232310e-01, 2.14196026e-01, 4.80008562e-01, 1.53476623e-01,
        2.88287558e-01, 2.01093123e-01, 5.05317416e-02, 2.76652670e-01,
        2.71036926e-01, 4.56721577e-01],
       [1.36343696e-02, 2.51257829e-02, 5.63063244e-02, 1.80032299e-02,
        3.38169234e-02, 2.35887764e-02, 5.92751226e-03, 3.24521190e-02,
        3.17933768e-02, 5.35746971e-02],
       [5.18168054e-03, 9.54894025e-03, 2.13989641e-02, 6.84204616e-03,
   

In [31]:
#98.Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [32]:
#99.Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [33]:
#100.Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17720025  0.26624952]
