<a href="https://colab.research.google.com/github/shruthymenon/Numpy-Task-2/blob/main/NUMPY_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. Import the numpy package under the name np
import numpy as np

In [ ]:
#2.Print the numpy version and the configuration
np.__version__

'1.21.6'

In [ ]:
#3.Create a null vector of size 10
a=np.zeros(10,dtype='int' )
a


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#4.How to find the memory size of any array 

print(a.size,a.itemsize)#total no of elements #memory size of elements


10 8


In [ ]:
#5. How to get the documentation of the numpy add function from the command line? (★☆☆)
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7f2099256690>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

In [ ]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
#7. Create a vector with values ranging from 10 to 49 (★☆☆)
b=np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#8 Reverse a vector (first element becomes last) (★☆☆)
print(b[::-1])


[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#10.Find indices of non-zero elements from [1,2,0,0,4,0]
a=[1,2,0,0,4,0]
for i in range(6):
  if a[i]!=0:
    print(i)

0
1
4


In [ ]:
#11.Create a 3x3 identity matrix 
a=np.eye(3,3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#12. Create a 3x3x3 array with random values
a=np.random.randint(0,100,size=(3,3,3))
print(a)

[[[25 71  2]
  [53 29 24]
  [83 18 44]]

 [[43 19 31]
  [31 77 16]
  [26 52 56]]

 [[16 10 39]
  [48 63 89]
  [34  2 67]]]


In [ ]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
a=np.random.rand(10,10)
print(a)
print(np.min(a))
print(np.max(a))

[[0.68055732 0.34932115 0.72055618 0.60015099 0.45612887 0.09396673
  0.08792159 0.40665425 0.89317968 0.08864326]
 [0.70556124 0.10415343 0.77493821 0.36505726 0.95874182 0.51956958
  0.45596424 0.04628309 0.3023252  0.60905418]
 [0.82091772 0.70441783 0.8459032  0.09512494 0.29719704 0.19217964
  0.22782834 0.54618979 0.28657282 0.60627814]
 [0.86188016 0.02570064 0.83833088 0.72425815 0.64090552 0.29074685
  0.91922232 0.18788372 0.86948121 0.18176173]
 [0.7504528  0.96312466 0.32138575 0.55835211 0.58142201 0.39286009
  0.11587764 0.28267463 0.79363703 0.2979257 ]
 [0.45476565 0.51296809 0.20496756 0.00270545 0.68095483 0.7645804
  0.68432064 0.95035496 0.40426233 0.79205647]
 [0.45337578 0.37372135 0.29387134 0.84670335 0.13801314 0.94158006
  0.54551409 0.62456065 0.57526497 0.08406823]
 [0.89858645 0.10872294 0.30928597 0.41281744 0.53862544 0.02071037
  0.03575563 0.71206325 0.40015716 0.84232461]
 [0.08809693 0.49868273 0.79253233 0.88617268 0.81929175 0.98799053
  0.92881116 

In [ ]:
#14.Create a random vector of size 30 and find the mean value 
a=np.random.randint(0,100,size=(30))
print(a)
print(np.mean(a))

[78 50 81  6 66  1 76 49 70 62 62 61 23 99 37 13 63 35 18 73 51  0  2 22
 86 11 22 79 99  2]
46.56666666666667


In [ ]:
#15. Create a 2d array with 1 on the border and 0 inside
a=np.ones([6,6],dtype=int)
print(a)
b=np.zeros([4,4],dtype=int)
print(b)
a[1:-1,1:-1]=b
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [ ]:
#16. How to add a border (filled with 0's) around an existing array? 
import numpy as np
a= np.random.randint(1,200,size=(6,6),dtype='int32')
print(a)
b=np.zeros((4,4))
a[:,0]= 0; a[0,:]=0;a[-1,:]=0;a[:,-1]=0
print(a)

[[ 70  15 189 137 151 177]
 [166 152  76  90 110  11]
 [ 73 105  46 195   3 169]
 [145 143 103 114  27  27]
 [ 86 199  28  79  79 124]
 [171 199   9   1  11  74]]
[[  0   0   0   0   0   0]
 [  0 152  76  90 110   0]
 [  0 105  46 195   3   0]
 [  0 143 103 114  27   0]
 [  0 199  28  79  79   0]
 [  0   0   0   0   0   0]]


In [ ]:
#17. What is the result of the following expression?
#(hint: NaN = not a number, inf = infinity)
import numpy as np
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [ ]:
#18.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
import numpy as np
a= np.zeros((5,5) )
print(a)
j=1;k=1
for i in range(1,5):
  a[i,j-1] = k  
  j=j+1;k+=1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
#19 Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
a=np.zeros((8,8))
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#20.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import numpy as np
a=np.ones((6,7,8))
m=0
for i in range(6):
  for j in range (7):
    for k in range(8):
      
      if(m==100):
       break
      m=m+1
print(i,j,k)

5 6 0


In [ ]:
#21.Create a checkerboard 8x8 matrix using the tile function
import numpy as np
A = np.array([[[[[[[[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]]]]]]]])
x = np.tile(A,reps=4)
print(x)

[[[[[[[[0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]]]]]]]]


In [ ]:
#22. Normalize a 5x5 random matrix
import numpy as np
a = np.random.rand(5,5)
print(a)
min=np.min(a);max=np.max(a)
a=(a-min)/(max-min)
print(a)

[[0.43042404 0.50507407 0.36347196 0.49910119 0.487247  ]
 [0.79752548 0.94031071 0.45485252 0.90436461 0.79006394]
 [0.56950445 0.88790466 0.11063609 0.09044992 0.14063367]
 [0.61368756 0.57738413 0.89225384 0.27846316 0.68639694]
 [0.94043441 0.57195446 0.60613172 0.75258775 0.3179559 ]]
[[0.39997685 0.48780202 0.32120826 0.48077498 0.46682862]
 [0.83186879 0.99985447 0.42871677 0.95756417 0.82309034]
 [0.56360384 0.93819917 0.02374886 0.         0.05904078]
 [0.61558492 0.57287422 0.94331594 0.22119608 0.70112693]
 [1.         0.56648627 0.60669554 0.7789999  0.26765898]]


In [ ]:
#23.Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [ ]:
#25.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#27. Consider an integer vector Z, which of these expressions are legal? 
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

ValueError: ignored

In [ ]:
# 28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-9.22337204e+18])

In [ ]:
# 29. How to round away from zero a float array ? (★☆☆)
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)


array([ 8.,  7., 10., -7., -9.,  9.,  2., -3.,  4., -8.])

In [ ]:
# 30. How to find common values between two arrays? (★☆☆)
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

In [ ]:
# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [ ]:
# 32. Is the following expressions true? (★☆☆)
print(np.sqrt(-1) == np.emath.sqrt(-1))  # False

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


In [ ]:
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
today = np.datetime64('today', 'D')
print("Today: ", today)
  
# for yesterday
yesterday = np.datetime64('today', 'D')
- np.timedelta64(1, 'D')
  
print("Yestraday: ", yesterday)
  
# for tomorrow
tomorrow = np.datetime64('today', 'D')
+ np.timedelta64(1, 'D')
  
print("Tomorrow: ", tomorrow)

Today:  2022-11-23
Yestraday:  2022-11-23
Tomorrow:  2022-11-23


In [ ]:
# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
# 36. Extract the integer part of a random array using 5 different methods (★★☆)
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)

array([-3.,  5., -7., -5.,  3.,  4.,  0.,  3.,  9., -8.])

In [ ]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
np.linspace(start=0, stop=11, num=10, endpoint=False)

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

In [ ]:
# 40. Create a random vector of size 10 and sort it (★★☆)
x = np.random.random(size=10)
x.sort()
print(x)

[0.02392405 0.05441597 0.14486998 0.18435972 0.39919631 0.53631181
 0.58710137 0.60210088 0.79940244 0.85677584]


In [ ]:
 #41. How to sum a small array faster than np.sum? (★★☆)
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

6.185054779052734
8.404970169067383


In [ ]:
# 42. Consider two random array A and B, check if they are equal (★★☆)
A = np.arange(10)
B = np.arange(10)
np.array_equal(A, B)

True

In [ ]:
 #43. Make an array immutable (read-only) (★★☆)
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1   # ValueError: assignment destination is read-only

ValueError: ignored

In [ ]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)


[0.83465029 1.19458474 1.16385554 0.09182107 0.93379693 0.37344846
 1.23376247 0.49395683 0.60028364 0.92147988]
[0.86086722 0.75657596 0.67902896 0.32284366 0.76062342 0.83139017
 0.66619657 1.29650312 1.20787928 0.77105275]


In [ ]:
# 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
x = np.random.random(10)
x[x == np.max(x)] = 0
x[x.argmax()] = 0
print(x)

[0.         0.23069277 0.77608753 0.         0.44664191 0.28365092
 0.27140319 0.13167547 0.57862439 0.80292021]


In [ ]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ 1.60057360e+04, -6.29045400e+07,  9.49623212e+06,
         6.81631403e+05, -1.23204027e+05],
       [-1.91753274e+06,  8.25142398e+04, -9.61777493e+02,
         1.13869446e+08,  5.94705171e+01],
       [ 2.06949745e+05, -8.78053127e+05, -1.46274167e+05,
        -1.40221101e+05,  2.66586052e+05],
       [-6.94427096e+06,  2.59124236e+05, -9.38972041e+06,
         8.25216872e+00, -3.47879616e+06],
       [ 2.92253665e+07, -4.37467580e+04, -1.88134204e+04,
         1.37837031e+04,  3.18776718e+02]])

In [ ]:
#48.Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps) 

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
#49. How to print all the values of an array? (★★☆)
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: ignored

In [ ]:
# 50 How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

57


In [ ]:
#51 Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [ ]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.79025772 0.90167508 0.49359852 0.71070945 0.85920451
  0.83175248 0.44097399 0.88745122 1.22279051]
 [0.79025772 0.         0.19697883 0.30187602 0.69137112 0.22117059
  0.0416209  0.40894519 0.32789758 0.66642715]
 [0.90167508 0.19697883 0.         0.41384224 0.62324639 0.06983676
  0.18390396 0.47291314 0.16447019 0.47044913]
 [0.49359852 0.30187602 0.41384224 0.         0.54063923 0.38126055
  0.3434154  0.13734739 0.43688749 0.80168201]
 [0.71070945 0.69137112 0.62324639 0.54063923 0.         0.55342053
  0.71758984 0.42262334 0.48437821 0.64858959]
 [0.85920451 0.22117059 0.06983676 0.38126055 0.55342053 0.
  0.22065856 0.42333621 0.10883047 0.45392712]
 [0.83175248 0.0416209  0.18390396 0.3434154  0.71758984 0.22065856
  0.         0.4487359  0.32939168 0.65384257]
 [0.44097399 0.40894519 0.47291314 0.13734739 0.42262334 0.42333621
  0.4487359  0.         0.44656179 0.79050896]
 [0.88745122 0.32789758 0.16447019 0.43688749 0.48437821 0.10883047
  0.32939168 0.44656

In [ ]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#54. How to read the following file? (★★☆)
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [ ]:
#55. What is the equivalent of enumerate for numpy arrays? (★★☆)
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
#56. Generate a generic 2D Gaussian-like array (★★☆)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [ ]:
#57. How to randomly place p elements in a 2D array? (★★☆)

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#58. Subtract the mean of each row of a matrix (★★☆)
X = np.random.rand(5, 10)


Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.40761483 -0.33149945  0.02196865 -0.41649107 -0.1478097   0.02893823
   0.51885444  0.07236445  0.07105961 -0.22499999]
 [-0.05782354  0.33356264  0.10523005 -0.22578726 -0.32010088 -0.29483608
   0.33073158  0.01748078  0.3243484  -0.21280568]
 [ 0.02366955  0.16948846 -0.51408182  0.04295907  0.14811642  0.41734827
  -0.09151031 -0.27144403 -0.07581525  0.15126964]
 [-0.03483535 -0.08071814 -0.01392362  0.06191373  0.27156191 -0.12002796
  -0.27057235  0.39341136 -0.57733118  0.3705216 ]
 [ 0.26562541 -0.27884935 -0.33357629  0.36156027  0.16226711  0.33689208
  -0.23342324  0.31642732 -0.28472055 -0.31220277]]


In [ ]:
#59. How to sort an array by the nth column? (★★☆)
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 0 4]
 [3 9 8]
 [9 3 6]]
[[7 0 4]
 [9 3 6]
 [3 9 8]]


In [ ]:
#60. How to tell if a given 2D array has null columns?
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [ ]:
#61. Find the nearest value from a given value in an array (★★☆)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4618884238132126


In [ ]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
#63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

In [ ]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 2. 4. 2. 2. 4. 6. 3. 2. 4.]


In [ ]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [ ]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[44 47 36 68]
 [48 43 58 32]
 [48 58 63 51]]
[[44 47 36 68]
 [48 43 58 32]
 [48 58 63 51]]


In [ ]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? 
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.41347166 0.4340333  0.50246364 0.50743584 0.39743589 0.43268291
 0.47515207 0.36939763 0.55716187 0.45252549]
0    0.413472
1    0.434033
2    0.502464
3    0.507436
4    0.397436
5    0.432683
6    0.475152
7    0.369398
8    0.557162
9    0.452525
dtype: float64


In [ ]:
#69. How to get the diagonal of a dot product?

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
  
np.diag(np.dot(A, B))

np.sum(A * B.T, axis=1)

np.einsum("ij,ji->i", A, B)

array([1.37583778, 1.38852276, 1.40339719, 0.98752047, 0.75101932])

In [ ]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]
